project_name: cvpm
before:
  hooks:
    - mkdir build
    - cp -r cli/. build/.
builds:
  -
    main: build/main.go
  - 
    goos:
      - freebsd
      - linux
      - windows
      - darwin
    binary: cvpm
    goarch:
      - amd64
      - arm
      - arm64
    env:
      - CGO_ENABLED=0
    goarm:
      - 5
      - 6
      - 7
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^tests:'
