language: go
sudo: required
git:
  clone: quiet

env:
# needed for the snap pipe:
  - GO111MODULE=on

script:
  - go test -race -v ./...
  - go build

go:
  - 1.12.x
  - master

matrix:
  allow_failures:
    - go: tip

install: true

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true